.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. placeh_qt test_placeh_qt
clean: FORCE
	$(MAKE) -C .. placeh_qt_clean test_placeh_qt_clean
check: FORCE
	$(MAKE) -C .. test_placeh_qt_check
placeh-qt placeh-qt.exe: FORCE
	 $(MAKE) -C .. placeh_qt
